_BASE_: "Base-RCNN-FPN.yaml"
MODEL:
  MASK_ON: True
  BACKBONE:
    NAME: "build_convnext_fpn_backbone"
  CONVNEXT:
    DEPTHS: [3, 3, 9, 3]
    DIMS: [96, 192, 384, 768]
    DROP_PATH_RATE: 0.2
    LAYER_SCALE_INIT_VALUE: 1e-6
    OUT_FEATURES: [0, 1, 2, 3]
  FPN:
    IN_FEATURES: [0, 1, 2, 3]
  ANCHOR_GENERATOR:
    SIZES: [[64], [128], [256], [512], [1024]]  # One size for each in feature map
    ASPECT_RATIOS: [[0.5, 1.0, 2.0]]  # Three aspect ratios (same for all in feature maps)
  RPN:
    IN_FEATURES: ["p2", "p3", "p4", "p5", "p6"]
    PRE_NMS_TOPK_TRAIN: 2000  # Per FPN level
    PRE_NMS_TOPK_TEST: 1000  # Per FPN level
    # Detectron1 uses 2000 proposals per-batch,
    # (See "modeling/rpn/rpn_outputs.py" for details of this legacy issue)
    # which is approximately 1000 proposals per-image since the default batch size for FPN is 2.
    POST_NMS_TOPK_TRAIN: 1000
    POST_NMS_TOPK_TEST: 1000
  ROI_HEADS:
    NAME: "StandardROIHeads"
    IN_FEATURES: ["p2", "p3", "p4", "p5"]
    NUM_CLASSES: 13
  ROI_BOX_HEAD:
    NAME: "FastRCNNConvFCHead"
    NUM_FC: 2
    POOLER_RESOLUTION: 7
  ROI_MASK_HEAD:
    NAME: "MaskRCNNConvUpsampleHead"
    NUM_CONV: 4
    POOLER_RESOLUTION: 14
INPUT:
  FORMAT: "RGB"
SOLVER:
  WEIGHT_DECAY: 0.05
  WEIGHT_DECAY_RATE: 0.95
  OPTIMIZER: "ADAMW"
  AMP:
    ENABLED: True
DATASETS:
  TRAIN: ("coco_2017_train",)
  TEST: ("coco_2017_val",)
